

onEvent('recipes', event => {

  event.remove({mod: 'mcda'})
  event.remove({mod: 'mcdw'})
  event.remove({mod: 'adventurez'})
  event.remove({mod: 'waystones'})
  event.remove({mod: 'biomemakeover'})
  event.remove({mod: 'bosses_of_mass_destruction'})
  event.remove({mod: 'botania'})  
  event.remove({mod: 'bountiful'})  
  event.remove({mod: 'mobz'})
  event.remove({mod: 'gateofbabylon'}) 
  event.remove({mod: 'xtraarrows'}) 
  event.remove({mod: 'dynocaps'}) 
  event.remove({mod: 'elementalcreepers'}) 
  event.remove({mod: 'expandedstorage'}) 
  event.remove({mod: 'interactic'})
  event.remove({mod: 'heartbond'})
  event.remove({mod: 'icarus'})    
  event.remove({mod: 'hookshot'})  
  event.remove({mod: 'inmis'}) 
  event.remove({mod: 'spectrum'}) 
  event.remove({mod: 'terrarianslimes'})  
  event.remove({mod: 'graveyard'}) 
  event.remove({mod: 'things'}) 
  event.remove({mod: 'titlescrolls'}) 
  event.remove({mod: 'trapexpansion'})
  event.remove({mod: 'villager-hat'})
  
  
  
  
  event.remove({output: 'valley:fur_chestplate'}) 
  event.remove({output: 'valley:flint_rock'}) 
  event.remove({output: 'valley:bone_knife'}) 
  event.remove({output: 'valley:climbing_axe'})   
  event.remove({output: 'valley:tongs'}) 
  event.remove({output: 'valley:lumber_axe'}) 
  event.remove({output: 'valley:prismarine_scalpel'})
  
  event.remove({output: 'valley:wood_knife'}) 
  event.remove({output: 'valley:stone_knife'}) 
  event.remove({output: 'valley:golden_knife'}) 
  event.remove({output: 'valley:iron_knife'}) 
  event.remove({output: 'valley:netherite_knife'})   
  event.remove({output: 'valley:diamond_knife'})     
  event.remove({output: 'valley:rg_knife'}) 

  event.remove({output: 'valley:wood_sickle'}) 
  event.remove({output: 'valley:stone_sickle'}) 
  event.remove({output: 'valley:golden_sickle'}) 
  event.remove({output: 'valley:iron_sickle'}) 
  event.remove({output: 'valley:netherite_sickle'})   
  event.remove({output: 'valley:diamond_sickle'})     
  event.remove({output: 'valley:rg_sickle'}) 

  event.remove({output: 'valley:wood_hatchet'}) 
  event.remove({output: 'valley:stone_hatchet'}) 
  event.remove({output: 'valley:golden_hatchet'}) 
  event.remove({output: 'valley:iron_hatchet'}) 
  event.remove({output: 'valley:netherite_hatchet'})   
  event.remove({output: 'valley:diamond_hatchet'})     
  event.remove({output: 'valley:rg_hatchet'}) 
  
  event.remove({output: 'valley:rg_shovel'}) 
  event.remove({output: 'valley:rg_pickaxe'}) 
  event.remove({output: 'valley:rg_axe'})   
  event.remove({output: 'valley:rg_hoe'})     
  event.remove({output: 'valley:rg_sword'})
  
  event.remove({output: 'valley:rg_helmet'}) 
  event.remove({output: 'valley:rg_chestplate'}) 
  event.remove({output: 'valley:rg_leggings'})   
  event.remove({output: 'valley:rg_boots'})     

  event.remove({output: 'valley:spike_wall_block'})  
 

  event.remove({output: 'valley:copper_billet'})   
  event.remove({output: 'valley:fiber'})
  event.remove({output: 'valley:bait'}) 
  event.remove({output: 'valley:glistering_bait'}) 
  event.remove({output: 'valley:null_totem'})
  event.remove({output: 'valley:lingering_powder'})   
  
  event.remove({id: 'blockus:rainbow_block'})

  event.remove({id: 'blockus:asphalt'})
  event.remove({id: 'blockus:white_asphalt'})
  event.remove({id: 'blockus:orange_asphalt'})
  event.remove({id: 'blockus:magenta_asphalt'})
  event.remove({id: 'blockus:light_blue_asphalt'})
  event.remove({id: 'blockus:yellow_asphalt'})
  event.remove({id: 'blockus:lime_asphalt'})
  event.remove({id: 'blockus:pink_asphalt'})
  event.remove({id: 'blockus:light_gray_asphalt'})
  event.remove({id: 'blockus:gray_asphalt'})
  event.remove({id: 'blockus:cyan_asphalt'})
  event.remove({id: 'blockus:purple_asphalt'})
  event.remove({id: 'blockus:blue_asphalt'})
  event.remove({id: 'blockus:brown_asphalt'})
  event.remove({id: 'blockus:green_asphalt'})
  event.remove({id: 'blockus:red_asphalt'})

  event.remove({id: 'blockus:asphalt_stairs'})
  event.remove({id: 'blockus:white_asphalt_stairs'})
  event.remove({id: 'blockus:orange_asphalt_stairs'})
  event.remove({id: 'blockus:magenta_asphalt_stairs'})
  event.remove({id: 'blockus:light_blue_asphalt_stairs'})
  event.remove({id: 'blockus:yellow_asphalt_stairs'})
  event.remove({id: 'blockus:lime_asphalt_stairs'})
  event.remove({id: 'blockus:pink_asphalt_stairs'})
  event.remove({id: 'blockus:light_gray_asphalt_stairs'})
  event.remove({id: 'blockus:gray_asphalt_stairs'})
  event.remove({id: 'blockus:cyan_asphalt_stairs'})
  event.remove({id: 'blockus:purple_asphalt_stairs'})
  event.remove({id: 'blockus:blue_asphalt_stairs'})
  event.remove({id: 'blockus:brown_asphalt_stairs'})
  event.remove({id: 'blockus:green_asphalt_stairs'})
  event.remove({id: 'blockus:red_asphalt_stairs'})

  event.remove({id: 'blockus:asphalt_slab'})
  event.remove({id: 'blockus:white_asphalt_slab'})
  event.remove({id: 'blockus:orange_asphalt_slab'})
  event.remove({id: 'blockus:magenta_asphalt_slab'})
  event.remove({id: 'blockus:light_blue_asphalt_slab'})
  event.remove({id: 'blockus:yellow_asphalt_slab'})
  event.remove({id: 'blockus:lime_asphalt_slab'})
  event.remove({id: 'blockus:pink_asphalt_slab'})
  event.remove({id: 'blockus:light_gray_asphalt_slab'})
  event.remove({id: 'blockus:gray_asphalt_slab'})
  event.remove({id: 'blockus:cyan_asphalt_slab'})
  event.remove({id: 'blockus:purple_asphalt_slab'})
  event.remove({id: 'blockus:blue_asphalt_slab'})
  event.remove({id: 'blockus:brown_asphalt_slab'})
  event.remove({id: 'blockus:green_asphalt_slab'})
  event.remove({id: 'blockus:red_asphalt_slab'})
})

