# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				glow_squid = true
				bat = true
				squid = true
				salmon = true
				polar_bear = true
				chest_minecart = true
				item = true
				villager = true
				cow = true
				chicken = true
				horse = true
				iron_golem = true
				cat = true
				sheep = true
				donkey = true
				parrot = true
				pig = true
				wolf = true
				zombie = true
				spider = true
				skeleton = true
				creeper = true
				enderman = true
				zombie_villager = true
				drowned = true
				area_effect_cloud = true
				witch = true
				arrow = true
				potion = true
				fox = true
				snowball = true
				goat = true
				armor_stand = true
				item_frame = true
				rabbit = true
				phantom = true
				experience_orb = true
				experience_bottle = true
				cave_spider = true

			[light_sources.settings.entities.betteranimalsplus]
				jellyfish = true
				shark = true
				whale = true
				badger = true
				pheasant = true
				deer = true
				brownbear = true
				goose = true
				songbird = true
				boar = true
				coyote = true
				butterfly = true
				badgerdirt = true
				eel_freshwater = true
				lamprey = true
				tarantula = true
				squirrel = true
				crab = true
				feralwolf = true
				horseshoecrab = true

			[light_sources.settings.entities.valley]
				sardine = true
				duck = true

			[light_sources.settings.entities.earth]
				rubro = true

			[light_sources.settings.entities.mobz]
				toad = true

			[light_sources.settings.entities.graveyard]
				skeleton_creeper = true
				revenant = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.terrarianslimes]
				red_slime = true
				black_slime = true
				yellow_slime = true
				green_slime = true
				mother_slime = true
				blue_slime = true
				ice_slime = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

			[light_sources.settings.entities.creeperoverhaul]
				dripstone_creeper = true
				cave_creeper = true
				jungle_creeper = true
				swamp_creeper = true
				snowy_creeper = true

			[light_sources.settings.entities.elementalcreepers]
				light_creeper = true
				earth_creeper = true
				cookie_creeper = true
				dark_creeper = true
				firework_creeper = true
				electric_creeper = true
				reverse_creeper = true
				illusion_creeper = true
				water_creeper = true
				hydrogen_creeper = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.botania]
				player_mover = true

			[light_sources.settings.entities.spectrum]
				shooting_star = true

			[light_sources.settings.entities.adventurez]
				deer = true

			[light_sources.settings.entities.mythicmounts]
				geckotoalizard = true
				dragon = true

			[light_sources.settings.entities.hookshot]
				hookshot = true

